#
# Configuration for the built-in toolchain.
#
kind: BuiltinToolchain

#
# Configuration of the default build container.
#

## container:
##   # Builder image.
##   image: getenvoy/extension-rust-builder:0.2.0
##   # Docker cli options.
##   options: []

#
# Configuration of the 'build' command.
#
# If omitted, configuration of the default build container will be used instead.
#

## build:
##   container:
##     # Builder image.
##     image: getenvoy/extension-rust-builder:0.2.0
##     # Docker cli options.
##     options: []
##   output:
##     # Output *.wasm file.
##     wasmFile: target/getenvoy/extension.wasm

#
# Configuration of the 'test' command.
#
# If omitted, configuration of the default build container will be used instead.
#

## test:
##   container:
##     # Builder image.
##     image: getenvoy/extension-rust-builder:0.2.0
##     # Docker cli options.
##     options: []

#
# Configuration of the 'clean' command.
#
# If omitted, configuration of the default build container will be used instead.
#

## clean:
##   container:
##     # Builder image.
##     image: getenvoy/extension-rust-builder:0.2.0
##     # Docker cli options.
##     options: []
